### ISSUE TITLE
tntnet can't load the library

### ISSUE THREAD

**Issue by FrancoisRegisDegott-eaton** [42ity/fty-asset-mapping-rest#18]
from UI, try to map a basic credential to a device (upgrade device firmware)....
i get a 404 not found on POST /api/v1/admin/communication-data/communications

extract of tntnet@bios logs...

Aug 20 09:52:38 eaton-rc-080027085465 tntnet[8517]: [14B blob data]
Aug 20 09:52:38 eaton-rc-080027085465 tntnet[8517]: 2021-08-20 09:52:38.06791 [8517.140063027115776] INFO tntnet.comploader - load library "libfty_asset_mapping_rest"
Aug 20 09:52:38 eaton-rc-080027085465 tntnet[8517]: 2021-08-20 09:52:38.06799 [8517.140063027115776] WARN tntnet.comploader - failed to load library "/usr/lib/bios/libfty_asset_mapping_rest"
Aug 20 09:52:38 eaton-rc-080027085465 tntnet[8517]: 2021-08-20 09:52:38.06804 [8517.140063027115776] WARN tntnet.comploader - failed to load library "/usr/lib/x86_64-linux-gnu/libfty_asset_mapping_rest"
Aug 20 09:52:38 eaton-rc-080027085465 tntnet[8517]: 2021-08-20 09:52:38.06808 [8517.140063027115776] WARN tntnet.comploader - failed to load library "/usr/lib/x86_64-linux-gnu/fty_rest/libfty_asset_mapping_rest"
Aug 20 09:52:38 eaton-rc-080027085465 tntnet[8517]: 2021-08-20 09:52:38.06812 [8517.140063027115776] WARN tntnet.comploader - failed to load library "/usr/libexec/bios/libfty_asset_mapping_rest"
Aug 20 09:52:38 eaton-rc-080027085465 tntnet[8517]: 2021-08-20 09:52:38.06815 [8517.140063027115776] WARN tntnet.comploader - failed to load library "./libfty_asset_mapping_rest"
Aug 20 09:52:38 eaton-rc-080027085465 tntnet[8517]: 2021-08-20 09:52:38.06818 [8517.140063027115776] WARN tntnet.comploader - failed to load library "/usr/lib/tntnet/libfty_asset_mapping_rest"
Aug 20 09:52:38 eaton-rc-080027085465 tntnet[8517]: 2021-08-20 09:52:38.06835 [8517.140063027115776] WARN tntnet.comploader - failed to load library "libfty_asset_mapping_rest"
Aug 20 09:52:38 eaton-rc-080027085465 tntnet[8517]: 2021-08-20 09:52:38.06839 [8517.140063027115776] WARN tntnet.worker - library libfty_asset_mapping_rest not found
Aug 20 09:52:38 eaton-rc-080027085465 tntnet[8517]: 2021-08-20 09:52:38.06852 [8517.140063027115776] INFO tntnet.worker - request POST /api/v1/admin/communication-data/communications ready, returncode 404 Not Found - ContentSize: 239

Related notes:
- misleading between '-' and '_' in projectName, libName (see .xml conf file)
- please, avoid hardcoding path in CMakelists.txt  (/usr/bin/bios), prefer prefix with CMAKE gnu installation variables

**Comment by etnKlendathu** [comment]
`please, avoid hardcoding path in CMakelists.txt (/usr/bin/bios), prefer prefix with CMAKE installation variables`
This is a rest module with non standard install path (don't ask me why) some of modules installing into this path.
So, you prefer ${CMAKE_CMAKE_INSTALL_FULL_LIBDIR}/bios? But in this case it could be /usr/lib/bios or /usr/lib64/bios... IMHO in this case not deterministic to use it in tntnet.

**Comment by perrettecl** [comment]
Good catch @jeffdegott!

@jeffdegott  @m-cid and @etnKlendathu Regarding the "/usr/lib/bios" is a special case and cannot be done using CMAKE variable easily. In such case I'm in favor to hardcode it, as it's more readable for everybody.

**Comment by etnKlendathu** [comment]
fixed

**Comment by FrancoisRegisDegott-eaton** [comment]
> 
> 
> Good catch @jeffdegott!
> 
> @jeffdegott @m-cid and @etnKlendathu Regarding the "/usr/lib/bios" is a special case and cannot be done using CMAKE variable easily. In such case I'm in favor to hardcode it, as it's more readable for everybody.

1/ minimum prefix with CMAKE_INSTALL_PREFIX   (usr)
2/ lot of rest libs are installed in CMAKE_INSTALL_FULL_LIBDIR (gnu std)
3/ by the way, no matter  ;)
